package ProyectoFinal.forms;

import javax.swing.JOptionPane;
import ProyectoFinal.Usuario;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.security.*;

/**
 *
 * @author Juan Samayoa
 * Carne: 9390-23-2010
 * Programación II
 */
public class InicioSesionForm extends javax.swing.JFrame {
    /**
     * Creates new form InicioSesionForm
     */
    
    public static final String user = "admindb";
    public static final String password = "root";
    public static final String bd = "SistemaRRHH";
    public static final String ip = "localhost";
    public static final String port = "1433";
    
    PreparedStatement ps;
    ResultSet rs;
    
    public InicioSesionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTextLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        UsernameTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ExitSystemButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(300, 300));

        MainTextLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        MainTextLabel.setText("Portal Recursos Humanos");

        DescriptionLabel.setText("Bienvenido al portal de recursos humanos, \npor favor ingrese su nombre de usuario y contraseña");

        LoginBtn.setText("Iniciar Sesión");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        UsernameLabel.setText("Nombre de usuario:");

        PasswordLabel.setText("Contraseña:");

        ExitSystemButton.setText("Salir del sistema");
        ExitSystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSystemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(MainTextLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(DescriptionLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UsernameLabel)
                                    .addComponent(PasswordLabel))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(LoginBtn)))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ExitSystemButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(MainTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(DescriptionLabel)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel))
                .addGap(46, 46, 46)
                .addComponent(LoginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(ExitSystemButton)
                .addContainerGap())
        );

        UsernameTxt.getAccessibleContext().setAccessibleName("usernameTxt");
        PasswordTxt.getAccessibleContext().setAccessibleName("passwordTxt");
        PasswordTxt.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Validador
    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        String usr = UsernameTxt.getText();
        String pass = new String(PasswordTxt.getPassword());
        Connection conn = null;
        
        //Contraseña encriptada
        String passe = "";
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(pass.getBytes());
            byte[] digest = md.digest();
            passe = String.format("%064x", new java.math.BigInteger(1, digest));
        } catch (NoSuchAlgorithmException e) {
            System.out.println("Error al encriptar la contraseña: " + e);
        }
        
        //Validar inicio de sesión
        boolean exito = Usuario.iniciarSesion(usr, passe);
        if (exito) {
           // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this,
                "Ha iniciado sesion correctamente. Bienvenido " + usr,
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            MenuPrincipalForm menup = new MenuPrincipalForm(Usuario.obtenerUsuario(usr));
            menup.setVisible(true);
            UsernameTxt.setText("");
            PasswordTxt.setText("");
            // Agregar un WindowListener para detectar el cierre del formulario o un dispose del mismo
            menup.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    System.out.println("Cerrando el menu principal...");
                    setVisible(true);
                }
            });
        } else {
            //mostrar mensaje de error
            JOptionPane.showMessageDialog(this,
                "Usuario o contraseña incorrectos. Por favor intente de nuevo.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void ExitSystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitSystemButtonActionPerformed
        //Mostrar mensaje si desea cerrar sesion o no
        int dialogResult = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir del sistema?", "Advertencia", JOptionPane.YES_NO_OPTION);
        
        if (dialogResult == JOptionPane.YES_OPTION) {
            System.out.println("Saliendo del sistema...");
            System.exit(0);
        } else {
            System.out.println("Se ha cancelado la operacion de cerrar sistema.");
        }
    }//GEN-LAST:event_ExitSystemButtonActionPerformed

    private static Connection connectDatabase(){
        Connection conexion = null;
        String conn = "jdbc:sqlserver://" + ip + ":" + port + "/" + bd;
        
        try {
            String cadena = "jdbc:sqlserver://localhost:1433;databaseName=SistemaRRHH;encrypt=true;trustServerCertificate=true";
            conexion = DriverManager.getConnection(cadena, user, password);
            JOptionPane.showMessageDialog(null, "Conexión exitosamente a la Base de Datos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al conectar a la base de datos: " + e.toString());
            System.out.println(e);
            System.exit(0);
        }
        return conexion;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        connectDatabase();
        Usuario.obtenerTodosLosUsuarios();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InicioSesionForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JButton ExitSystemButton;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel MainTextLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTxt;
    // End of variables declaration//GEN-END:variables

}
