/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoFinal.forms;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import ProyectoFinal.RecentHiringsReport; // FIXED: Use new report class
import ProyectoFinal.Utils;


/**
 *
 * @author User
 */
public class RecentHiringForm extends javax.swing.JFrame {

    /**
     * Creates new form ContratacionRecienteForm
     */
    public RecentHiringForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecentHiringReportLabel = new javax.swing.JLabel();
        ReturnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        QueryRecentContractsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RecentHiringReportLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        RecentHiringReportLabel.setText("Reporte de Contrataciones Recientes");

        ReturnButton.setText("Regresar al Menú Principal");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        QueryRecentContractsButton.setText("Consultar contrataciones recientes");
        QueryRecentContractsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryRecentContractsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(RecentHiringReportLabel)
                .addGap(314, 314, 314))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QueryRecentContractsButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RecentHiringReportLabel)
                .addGap(18, 18, 18)
                .addComponent(QueryRecentContractsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void QueryRecentContractsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueryRecentContractsButtonActionPerformed
        // Ask user for date range (both dates are optional)
        String fechaInicio = JOptionPane.showInputDialog(this,
            "Ingrese la fecha de inicio para el reporte (dd/MM/yyyy) - OPCIONAL:\nDeje vacío para buscar desde el inicio de los tiempos",
            "Fecha de inicio (Opcional)",
            JOptionPane.QUESTION_MESSAGE);

        // Allow empty or null start date
        if (fechaInicio != null && !fechaInicio.trim().isEmpty() && !Utils.validateDate(fechaInicio)) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use dd/MM/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String fechaFin = JOptionPane.showInputDialog(this,
            "Ingrese la fecha de fin para el reporte (dd/MM/yyyy) - OPCIONAL:\nDeje vacío para buscar hasta el fin de los tiempos",
            "Fecha de fin (Opcional)",
            JOptionPane.QUESTION_MESSAGE);

        // Allow empty or null end date
        if (fechaFin != null && !fechaFin.trim().isEmpty() && !Utils.validateDate(fechaFin)) {
            JOptionPane.showMessageDialog(this, "Formato de fecha de fin inválido. Use dd/MM/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convert empty strings to null for flexible search
        String startDate = (fechaInicio == null || fechaInicio.trim().isEmpty()) ? null : fechaInicio;
        String endDate = (fechaFin == null || fechaFin.trim().isEmpty()) ? null : fechaFin;

        // Validate date range only if both dates are provided
        if (startDate != null && endDate != null && !Utils.validateDateRange(startDate, endDate)) {
            JOptionPane.showMessageDialog(this, "La fecha de fin debe ser posterior a la fecha de inicio.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // FIXED: Use RecentHiringsReport instead of Reportes
            ArrayList<RecentHiringsReport> reportData = RecentHiringsReport.generateRecentHiringsReport(startDate, endDate);

            // Create table model
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Contrato");
            model.addColumn("ID Empleado");
            model.addColumn("Nombre");
            model.addColumn("Apellido");
            model.addColumn("Fecha Contratación");
            model.addColumn("Fecha Inicio Contrato");
            model.addColumn("Tipo Contrato");
            model.addColumn("Duración (meses)");
            model.addColumn("Salario");

            // Load data into table
            for (RecentHiringsReport report : reportData) {
                Object[] row = new Object[9];
                row[0] = report.getContractId();
                row[1] = report.getEmployeeId();
                row[2] = report.getFirstName();
                row[3] = report.getLastName();
                row[4] = report.getHiringDate();
                row[5] = report.getContractStartDate();
                row[6] = report.getContractType();
                row[7] = report.getDuration();
                row[8] = String.format("Q %.2f", report.getSalary());
                model.addRow(row);
            }

            jTable1.setModel(model);

            if (reportData.isEmpty()) {
                String dateRange = "todas las fechas";
                if (startDate != null && endDate != null) {
                    dateRange = "desde " + startDate + " hasta " + endDate;
                } else if (startDate != null) {
                    dateRange = "desde " + startDate;
                } else if (endDate != null) {
                    dateRange = "hasta " + endDate;
                }
                
                JOptionPane.showMessageDialog(this,
                    "No se encontraron contrataciones para el período: " + dateRange,
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Reporte generado exitosamente. Se encontraron " + reportData.size() + " contrataciones.",
                    "Reporte completo",
                    JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al generar el reporte: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_QueryRecentContractsButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecentHiringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecentHiringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecentHiringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecentHiringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecentHiringForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QueryRecentContractsButton;
    private javax.swing.JLabel RecentHiringReportLabel;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
