package ProyectoFinal.forms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ProyectoFinal.Utils;
import ProyectoFinal.User;

/**
 * User Management Form - Handles user CRUD operations
 * @author User
 */
public class UserManagementForm extends javax.swing.JFrame {

    /**
     * Creates new form UserManagementForm
     */
    public UserManagementForm() {
        initComponents();
        loadUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffManagementGrid = new javax.swing.JScrollPane();
        StaffManagementTable = new javax.swing.JTable();
        ReturnButton = new javax.swing.JButton();
        UserManagementLabel = new javax.swing.JLabel();
        UserIdTxt = new javax.swing.JTextField();
        UserNameTxt = new javax.swing.JTextField();
        FullNameTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        PhoneNumberTxt = new javax.swing.JTextField();
        UserTypeComboBox = new javax.swing.JComboBox<>();
        UpdateButton = new javax.swing.JButton();
        LoadButton = new javax.swing.JButton();
        UserIdLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        FullNameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        UserTypeLabel = new javax.swing.JLabel();
        CleanButton = new javax.swing.JButton();
        TerminationButton = new javax.swing.JButton();
        CreateUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        StaffManagementTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        StaffManagementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        StaffManagementTable.setShowGrid(true);
        StaffManagementTable.setShowVerticalLines(false);
        StaffManagementTable.setUpdateSelectionOnSort(false);
        StaffManagementTable.setVerifyInputWhenFocusTarget(false);
        StaffManagementGrid.setViewportView(StaffManagementTable);

        ReturnButton.setText("Regresar al Menú Principal");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        UserManagementLabel.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        UserManagementLabel.setText("Gestión de Usuarios");

        UserIdTxt.setEditable(false);
        UserIdTxt.setToolTipText("ID Usuario");
        UserIdTxt.setFocusable(false);
        UserIdTxt.setHighlighter(null);

        UserNameTxt.setToolTipText("Ej: PedroPerez");

        FullNameTxt.setToolTipText("Ej: Pedro Alberto Martinez");

        EmailTxt.setToolTipText("Ej: pedro@rrhh.com");

        PhoneNumberTxt.setToolTipText("Ej: 50502020");

        UserTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Administrador", "Reclutador", "Operador" }));
        UserTypeComboBox.setToolTipText("");

        UpdateButton.setText("Modificar información");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        LoadButton.setText("Seleccionar usuario");
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });

        UserIdLabel.setText("ID del Usuario:");

        UserNameLabel.setText("Nombre de usuario:");

        FullNameLabel.setText("Nombre completo:");

        EmailLabel.setText("Correo electrónico:");

        PhoneNumberLabel.setText("No. de teléfono:");

        UserTypeLabel.setText("Tipo de usuario:");

        CleanButton.setText("Limpiar campos");
        CleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanButtonActionPerformed(evt);
            }
        });

        TerminationButton.setText("Dar de baja (Eliminar)");
        TerminationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminationButtonActionPerformed(evt);
            }
        });

        CreateUserButton.setText("Crear Usuario");
        CreateUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ReturnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(UserTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PhoneNumberTxt)
                        .addComponent(EmailTxt)
                        .addComponent(FullNameTxt)
                        .addComponent(UserManagementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UserIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserNameTxt))
                    .addComponent(UserIdLabel)
                    .addComponent(UserNameLabel)
                    .addComponent(FullNameLabel)
                    .addComponent(EmailLabel)
                    .addComponent(PhoneNumberLabel)
                    .addComponent(UserTypeLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CleanButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TerminationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoadButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateUserButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(StaffManagementGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserManagementLabel)
                        .addGap(19, 19, 19)
                        .addComponent(UserIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FullNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CreateUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TerminationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CleanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StaffManagementGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        //cerrar el form actual definitivamente
        this.dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // Request confirmation for user information update
        int dialogResult = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea actualizar la información del usuario seleccionado?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.NO_OPTION){
            return;
        }
        
        // Update selected user information
        int selectedRow = StaffManagementTable.getSelectedRow();
        if(selectedRow >= 0 && !UserIdTxt.getText().equals("") && Integer.parseInt(UserIdTxt.getText()) > 0){
            // Get input data
            int userId = Integer.parseInt(UserIdTxt.getText());
            String username = UserNameTxt.getText();
            String fullName = FullNameTxt.getText();
            String email = EmailTxt.getText();
            String phone = PhoneNumberTxt.getText();
            String userType = UserTypeComboBox.getSelectedItem().toString();
            String password = JOptionPane.showInputDialog("Ingrese la contraseña del usuario (opcional para actualización):");

            if("".equals(username) || username == null){
                JOptionPane.showMessageDialog(null, "No se ha ingresado el nombre de usuario.", "Error al obtener nombre de usuario", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            if("".equals(fullName) || fullName == null){
                JOptionPane.showMessageDialog(null, "No se ha ingresado el nombre completo.", "Error al obtener nombre", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if("".equals(email) || email == null){
                JOptionPane.showMessageDialog(null, "No se ha ingresado el correo electrónico.", "Error al obtener correo electrónico", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(!Utils.validateEmail(email)){
                JOptionPane.showMessageDialog(null, "El correo electrónico ingresado no es válido.", "Error en formato de correo electrónico", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if("".equals(phone) || phone == null){
                JOptionPane.showMessageDialog(null, "No se ha ingresado el número de teléfono.", "Error al obtener número telefónico", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(!Utils.validatePhone(phone)){
                JOptionPane.showMessageDialog(null, "El número de teléfono ingresado no es válido.", "Error en formato de número telefónico", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(UserTypeComboBox.getSelectedIndex() <= 0){
                JOptionPane.showMessageDialog(null, "No se ha seleccionado el tipo de usuario.", "Error al obtener tipo de usuario", JOptionPane.ERROR_MESSAGE);
                return; 
            }

            // Update user using User.update() method
            boolean updated = User.update(userId, username, fullName, email, phone, password, userType);

            // Reload user information
            if(updated){
                JOptionPane.showMessageDialog(this, "Usuario actualizado exitosamente");
                User.getAll();
                loadUsers();
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido actualizar el usuario.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado un usuario válido.");
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        // Load selected user information from table
        int selectedRow = StaffManagementTable.getSelectedRow();
        if(selectedRow >= 0){
            UserIdTxt.setText(StaffManagementTable.getValueAt(selectedRow, 0).toString());
            UserNameTxt.setText(StaffManagementTable.getValueAt(selectedRow, 1).toString());
            FullNameTxt.setText(StaffManagementTable.getValueAt(selectedRow, 2).toString());
            EmailTxt.setText(StaffManagementTable.getValueAt(selectedRow, 3).toString());
            PhoneNumberTxt.setText(StaffManagementTable.getValueAt(selectedRow, 4).toString());

            // Set the user type in combo box
            String userType = StaffManagementTable.getValueAt(selectedRow, 5).toString();
            for(int i = 0; i < UserTypeComboBox.getItemCount(); i++){
                if(UserTypeComboBox.getItemAt(i).toString().equals(userType)){
                    UserTypeComboBox.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado un usuario.");
        }
    }//GEN-LAST:event_LoadButtonActionPerformed

    private void CleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanButtonActionPerformed
        // Clear all form fields
        UserIdTxt.setText("");
        UserNameTxt.setText("");
        FullNameTxt.setText("");
        EmailTxt.setText("");
        PhoneNumberTxt.setText("");
        UserTypeComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_CleanButtonActionPerformed

    private void TerminationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminationButtonActionPerformed
        // Request confirmation for user deletion
        int dialogResult = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar al usuario seleccionado?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.NO_OPTION){
            return;
        }
        
        // Delete selected user
        int selectedRow = StaffManagementTable.getSelectedRow();
        if(!UserIdTxt.getText().equals("") && selectedRow >= 0){
            int userId = Integer.parseInt(UserIdTxt.getText());
            // Use User.delete() method
            if(User.delete(userId)){
                JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente");
                User.getAll();
                loadUsers();
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido eliminar el usuario seleccionado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado un usuario.");
        }
    }//GEN-LAST:event_TerminationButtonActionPerformed

    private void CreateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserButtonActionPerformed
        // Request confirmation for user creation
        int dialogResult = JOptionPane.showConfirmDialog(null, "¿Deseas crear el usuario con la información ingresada?","Información",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.NO_OPTION){
            return;
        }
        
        // Create new user with input information
        String username = UserNameTxt.getText();
        String fullName = FullNameTxt.getText();
        String email = EmailTxt.getText();
        String phone = PhoneNumberTxt.getText();
        String userType = UserTypeComboBox.getSelectedItem().toString();
        String password = JOptionPane.showInputDialog("Ingrese la contraseña del usuario:");
        
        if("".equals(username) || username == null){
            JOptionPane.showMessageDialog(null, "No se ha ingresado el nombre de usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if("".equals(fullName) || fullName == null){
            JOptionPane.showMessageDialog(null, "No se ha ingresado el nombre completo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if("".equals(email) || email == null){
            JOptionPane.showMessageDialog(null, "No se ha ingresado el correo electrónico.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(!Utils.validateEmail(email)){
            JOptionPane.showMessageDialog(null, "El correo electrónico ingresado no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if("".equals(phone) || phone == null){
            JOptionPane.showMessageDialog(null, "No se ha ingresado el número de teléfono.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(!Utils.validatePhone(phone)){
            JOptionPane.showMessageDialog(null, "El número de teléfono ingresado no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(UserTypeComboBox.getSelectedIndex() <= 0){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado el tipo de usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if("".equals(password) || password == null){
            JOptionPane.showMessageDialog(null, "No se ha ingresado la contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Use User.add() method
        boolean created = User.add(username, fullName, email, phone, password, userType);

        if(created){
            JOptionPane.showMessageDialog(this, "Usuario creado exitosamente");
            User.getAll();
            loadUsers();
            CleanButtonActionPerformed(evt); // Clear fields after creation
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido crear el usuario.");
        }
    }//GEN-LAST:event_CreateUserButtonActionPerformed

    /**
     * Load users into the table from database
     */
    private void loadUsers(){
        User.getAll(); // Load all users from database
        DefaultTableModel model = new DefaultTableModel();

        // Define table columns
        model.addColumn("ID");
        model.addColumn("Usuario");
        model.addColumn("Nombre Completo");
        model.addColumn("Correo");
        model.addColumn("Teléfono");
        model.addColumn("Tipo Usuario");

        // Load user data into table
        for(User user : User.users){
            Object[] row = new Object[6];
            row[0] = user.getId();
            row[1] = user.getName();
            row[2] = user.getFullName();
            row[3] = user.getEmail();
            row[4] = user.getPhone();
            row[5] = user.getUserType();
            model.addRow(row);
        }

        StaffManagementTable.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CleanButton;
    private javax.swing.JButton CreateUserButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel FullNameLabel;
    private javax.swing.JTextField FullNameTxt;
    private javax.swing.JButton LoadButton;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField PhoneNumberTxt;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JScrollPane StaffManagementGrid;
    private javax.swing.JTable StaffManagementTable;
    private javax.swing.JButton TerminationButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel UserIdLabel;
    private javax.swing.JTextField UserIdTxt;
    private javax.swing.JLabel UserManagementLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JComboBox<String> UserTypeComboBox;
    private javax.swing.JLabel UserTypeLabel;
    // End of variables declaration//GEN-END:variables
}
